root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/app ./backend/cmd/app"
bin = "./tmp/app"
include_ext = ["go"]
exclude_dir = ["tmp", ".docker", ".docs", ".git", ".claude"]

[log]
main_only = true
