// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_confirmation_tokens.sql

package dbmodels

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getEmailConfirmationTokenByHash = `-- name: GetEmailConfirmationTokenByHash :one
SELECT
	token_uuid,
	user_uuid,
	token_hash,
	expires_at,
	used_at
FROM auth.email_confirmation_tokens
WHERE token_hash = $1
`

type GetEmailConfirmationTokenByHashRow struct {
	TokenUuid uuid.UUID
	UserUuid  uuid.UUID
	TokenHash string
	ExpiresAt time.Time
	UsedAt    *time.Time
}

func (q *Queries) GetEmailConfirmationTokenByHash(ctx context.Context, tokenHash string) (GetEmailConfirmationTokenByHashRow, error) {
	row := q.db.QueryRow(ctx, getEmailConfirmationTokenByHash, tokenHash)
	var i GetEmailConfirmationTokenByHashRow
	err := row.Scan(
		&i.TokenUuid,
		&i.UserUuid,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const insertEmailConfirmationToken = `-- name: InsertEmailConfirmationToken :exec
INSERT INTO auth.email_confirmation_tokens (
	token_uuid,
	user_uuid,
	token_hash,
	expires_at
)
VALUES
	($1, $2, $3, $4)
`

type InsertEmailConfirmationTokenParams struct {
	TokenUuid uuid.UUID
	UserUuid  uuid.UUID
	TokenHash string
	ExpiresAt time.Time
}

func (q *Queries) InsertEmailConfirmationToken(ctx context.Context, arg InsertEmailConfirmationTokenParams) error {
	_, err := q.db.Exec(ctx, insertEmailConfirmationToken,
		arg.TokenUuid,
		arg.UserUuid,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const invalidateActiveEmailConfirmationTokensByUser = `-- name: InvalidateActiveEmailConfirmationTokensByUser :execrows
UPDATE auth.email_confirmation_tokens
SET used_at = now()
WHERE user_uuid = $1
  AND used_at IS NULL
`

func (q *Queries) InvalidateActiveEmailConfirmationTokensByUser(ctx context.Context, userUuid uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, invalidateActiveEmailConfirmationTokensByUser, userUuid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markEmailConfirmationTokenUsed = `-- name: MarkEmailConfirmationTokenUsed :execrows
UPDATE auth.email_confirmation_tokens
SET used_at = now()
WHERE token_uuid = $1
  AND used_at IS NULL
`

func (q *Queries) MarkEmailConfirmationTokenUsed(ctx context.Context, tokenUuid uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markEmailConfirmationTokenUsed, tokenUuid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
