// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invitation_tokens.sql

package dbmodels

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getInvitationTokenByHash = `-- name: GetInvitationTokenByHash :one
SELECT
	token_uuid,
	email,
	role,
	token_hash,
	expires_at,
	used_at
FROM auth.invitation_tokens
WHERE token_hash = $1
`

type GetInvitationTokenByHashRow struct {
	TokenUuid uuid.UUID
	Email     string
	Role      string
	TokenHash string
	ExpiresAt time.Time
	UsedAt    *time.Time
}

func (q *Queries) GetInvitationTokenByHash(ctx context.Context, tokenHash string) (GetInvitationTokenByHashRow, error) {
	row := q.db.QueryRow(ctx, getInvitationTokenByHash, tokenHash)
	var i GetInvitationTokenByHashRow
	err := row.Scan(
		&i.TokenUuid,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const insertInvitationToken = `-- name: InsertInvitationToken :exec
INSERT INTO auth.invitation_tokens (
	token_uuid,
	email,
	role,
	token_hash,
	expires_at
)
VALUES
	($1, $2, $3, $4, $5)
`

type InsertInvitationTokenParams struct {
	TokenUuid uuid.UUID
	Email     string
	Role      string
	TokenHash string
	ExpiresAt time.Time
}

func (q *Queries) InsertInvitationToken(ctx context.Context, arg InsertInvitationTokenParams) error {
	_, err := q.db.Exec(ctx, insertInvitationToken,
		arg.TokenUuid,
		arg.Email,
		arg.Role,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const invalidateActiveInvitationTokensByEmail = `-- name: InvalidateActiveInvitationTokensByEmail :execrows
UPDATE auth.invitation_tokens
SET used_at = now()
WHERE email = $1
  AND used_at IS NULL
`

func (q *Queries) InvalidateActiveInvitationTokensByEmail(ctx context.Context, email string) (int64, error) {
	result, err := q.db.Exec(ctx, invalidateActiveInvitationTokensByEmail, email)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markInvitationTokenUsed = `-- name: MarkInvitationTokenUsed :execrows
UPDATE auth.invitation_tokens
SET used_at = now()
WHERE token_uuid = $1
  AND used_at IS NULL
`

func (q *Queries) MarkInvitationTokenUsed(ctx context.Context, tokenUuid uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markInvitationTokenUsed, tokenUuid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
