// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbmodels

import (
	"time"

	"github.com/google/uuid"
)

type AuthEmailConfirmationToken struct {
	TokenUuid uuid.UUID
	UserUuid  uuid.UUID
	TokenHash string
	ExpiresAt time.Time
	UsedAt    *time.Time
	CreatedAt time.Time
}

type AuthUser struct {
	UserUuid     uuid.UUID
	Email        string
	PasswordHash string
	Status       string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    *time.Time
}

type AuthUserRole struct {
	UserUuid  uuid.UUID
	Role      string
	GrantedAt time.Time
}
