// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: password_reset_tokens.sql

package dbmodels

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getPasswordResetTokenByHash = `-- name: GetPasswordResetTokenByHash :one
SELECT
	token_uuid,
	user_uuid,
	token_hash,
	expires_at,
	used_at
FROM auth.password_reset_tokens
WHERE token_hash = $1
`

type GetPasswordResetTokenByHashRow struct {
	TokenUuid uuid.UUID
	UserUuid  uuid.UUID
	TokenHash string
	ExpiresAt time.Time
	UsedAt    *time.Time
}

func (q *Queries) GetPasswordResetTokenByHash(ctx context.Context, tokenHash string) (GetPasswordResetTokenByHashRow, error) {
	row := q.db.QueryRow(ctx, getPasswordResetTokenByHash, tokenHash)
	var i GetPasswordResetTokenByHashRow
	err := row.Scan(
		&i.TokenUuid,
		&i.UserUuid,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const insertPasswordResetToken = `-- name: InsertPasswordResetToken :exec
INSERT INTO auth.password_reset_tokens (
	token_uuid,
	user_uuid,
	token_hash,
	expires_at
)
VALUES
	($1, $2, $3, $4)
`

type InsertPasswordResetTokenParams struct {
	TokenUuid uuid.UUID
	UserUuid  uuid.UUID
	TokenHash string
	ExpiresAt time.Time
}

func (q *Queries) InsertPasswordResetToken(ctx context.Context, arg InsertPasswordResetTokenParams) error {
	_, err := q.db.Exec(ctx, insertPasswordResetToken,
		arg.TokenUuid,
		arg.UserUuid,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const invalidateActivePasswordResetTokensByUser = `-- name: InvalidateActivePasswordResetTokensByUser :execrows
UPDATE auth.password_reset_tokens
SET used_at = now()
WHERE user_uuid = $1
  AND used_at IS NULL
`

func (q *Queries) InvalidateActivePasswordResetTokensByUser(ctx context.Context, userUuid uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, invalidateActivePasswordResetTokensByUser, userUuid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markPasswordResetTokenUsed = `-- name: MarkPasswordResetTokenUsed :execrows
UPDATE auth.password_reset_tokens
SET used_at = now()
WHERE token_uuid = $1
  AND used_at IS NULL
`

func (q *Queries) MarkPasswordResetTokenUsed(ctx context.Context, tokenUuid uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markPasswordResetTokenUsed, tokenUuid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
