// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

package dbmodels

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT
	token_id,
	user_uuid,
	family_id,
	parent_token_id,
	token_hash,
	expires_at,
	used_at,
	revoked_at,
	revocation_reason,
	created_at
FROM auth.refresh_tokens
WHERE token_hash = $1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (AuthRefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i AuthRefreshToken
	err := row.Scan(
		&i.TokenID,
		&i.UserUuid,
		&i.FamilyID,
		&i.ParentTokenID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
		&i.RevocationReason,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshTokenByHashForUpdate = `-- name: GetRefreshTokenByHashForUpdate :one
SELECT
	token_id,
	user_uuid,
	family_id,
	parent_token_id,
	token_hash,
	expires_at,
	used_at,
	revoked_at,
	revocation_reason,
	created_at
FROM auth.refresh_tokens
WHERE token_hash = $1
FOR UPDATE
`

// NOTE: UC-006 Q-5: 対象行を施錠し同時リフレッシュ（二重消費）を直列化する
func (q *Queries) GetRefreshTokenByHashForUpdate(ctx context.Context, tokenHash string) (AuthRefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHashForUpdate, tokenHash)
	var i AuthRefreshToken
	err := row.Scan(
		&i.TokenID,
		&i.UserUuid,
		&i.FamilyID,
		&i.ParentTokenID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
		&i.RevocationReason,
		&i.CreatedAt,
	)
	return i, err
}

const insertRefreshToken = `-- name: InsertRefreshToken :exec
INSERT INTO auth.refresh_tokens (
	token_id,
	user_uuid,
	family_id,
	parent_token_id,
	token_hash,
	expires_at
)
VALUES
	($1, $2, $3, $4, $5, $6)
`

type InsertRefreshTokenParams struct {
	TokenID       uuid.UUID
	UserUuid      uuid.UUID
	FamilyID      uuid.UUID
	ParentTokenID *uuid.UUID
	TokenHash     string
	ExpiresAt     time.Time
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, insertRefreshToken,
		arg.TokenID,
		arg.UserUuid,
		arg.FamilyID,
		arg.ParentTokenID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const markRefreshTokenUsed = `-- name: MarkRefreshTokenUsed :exec
UPDATE auth.refresh_tokens
SET used_at = now()
WHERE token_id = $1
`

// NOTE: UC-006 ローテーション: 使用済みは使用時刻で表す（INF-04・used_at＝消費）
func (q *Queries) MarkRefreshTokenUsed(ctx context.Context, tokenID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markRefreshTokenUsed, tokenID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE auth.refresh_tokens
SET revoked_at = now(),
    revocation_reason = $2
WHERE token_id = $1
`

type RevokeRefreshTokenParams struct {
	TokenID          uuid.UUID
	RevocationReason *string
}

// NOTE: UC-006 E3/E5/E6: 当該トークンのみ失効（revoked_at＝失効・used_atと別概念）
func (q *Queries) RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, arg.TokenID, arg.RevocationReason)
	return err
}

const revokeRefreshTokenFamily = `-- name: RevokeRefreshTokenFamily :exec
UPDATE auth.refresh_tokens
SET revoked_at = now(),
    revocation_reason = $2
WHERE family_id = $1
  AND revoked_at IS NULL
`

type RevokeRefreshTokenFamilyParams struct {
	FamilyID         uuid.UUID
	RevocationReason *string
}

// NOTE: UC-006 E4: 同一family（ローテーションチェーン）を一括失効（NFR-14・他familyは生かす）。既失効は上書きしない
func (q *Queries) RevokeRefreshTokenFamily(ctx context.Context, arg RevokeRefreshTokenFamilyParams) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokenFamily, arg.FamilyID, arg.RevocationReason)
	return err
}
