// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package dbmodels

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
	user_uuid,
	email,
	password_hash,
	status,
	created_at,
	updated_at
FROM auth.users
WHERE email = $1
  AND deleted_at IS NULL
`

type GetUserByEmailRow struct {
	UserUuid     uuid.UUID
	Email        string
	PasswordHash string
	Status       string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.UserUuid,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUuid = `-- name: GetUserByUuid :one
SELECT
	user_uuid,
	email,
	password_hash,
	status,
	created_at,
	updated_at
FROM auth.users
WHERE user_uuid = $1
  AND deleted_at IS NULL
`

type GetUserByUuidRow struct {
	UserUuid     uuid.UUID
	Email        string
	PasswordHash string
	Status       string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

// NOTE: UC-006: token→user 取得（削除済み除外・E5）
func (q *Queries) GetUserByUuid(ctx context.Context, userUuid uuid.UUID) (GetUserByUuidRow, error) {
	row := q.db.QueryRow(ctx, getUserByUuid, userUuid)
	var i GetUserByUuidRow
	err := row.Scan(
		&i.UserUuid,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserRoles = `-- name: GetUserRoles :many
SELECT
	role
FROM auth.user_roles
WHERE user_uuid = $1
ORDER BY role
`

func (q *Queries) GetUserRoles(ctx context.Context, userUuid uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserRoles, userUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var role string
		if err := rows.Scan(&role); err != nil {
			return nil, err
		}
		items = append(items, role)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertUser = `-- name: InsertUser :exec
INSERT INTO auth.users (
	user_uuid,
	email,
	password_hash,
	status
)
VALUES
	($1, $2, $3, $4)
`

type InsertUserParams struct {
	UserUuid     uuid.UUID
	Email        string
	PasswordHash string
	Status       string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.Exec(ctx, insertUser,
		arg.UserUuid,
		arg.Email,
		arg.PasswordHash,
		arg.Status,
	)
	return err
}

const insertUserRole = `-- name: InsertUserRole :exec
INSERT INTO auth.user_roles (
	user_uuid,
	role
)
VALUES
	($1, $2)
`

type InsertUserRoleParams struct {
	UserUuid uuid.UUID
	Role     string
}

func (q *Queries) InsertUserRole(ctx context.Context, arg InsertUserRoleParams) error {
	_, err := q.db.Exec(ctx, insertUserRole, arg.UserUuid, arg.Role)
	return err
}

const transitionUserStatus = `-- name: TransitionUserStatus :execrows
UPDATE auth.users
SET status = $2,
	updated_at = now()
WHERE user_uuid = $1
  AND status = $3
  AND deleted_at IS NULL
`

type TransitionUserStatusParams struct {
	UserUuid uuid.UUID
	Status   string
	Status_2 string
}

func (q *Queries) TransitionUserStatus(ctx context.Context, arg TransitionUserStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, transitionUserStatus, arg.UserUuid, arg.Status, arg.Status_2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserPassword = `-- name: UpdateUserPassword :execrows
UPDATE auth.users
SET password_hash = $2,
    updated_at = now()
WHERE user_uuid = $1
  AND deleted_at IS NULL
`

type UpdateUserPasswordParams struct {
	UserUuid     uuid.UUID
	PasswordHash string
}

// NOTE: UC-010: パスワード更新（削除済み除外）。0行=ユーザー不存在（削除レース）＝呼出側がTx全体を失敗させる
func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserPassword, arg.UserUuid, arg.PasswordHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
