// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package dbmodels

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countActiveSuperAdmins = `-- name: CountActiveSuperAdmins :one
SELECT count(*)
FROM auth.users u
JOIN auth.user_roles ur ON ur.user_uuid = u.user_uuid
WHERE ur.role = 'super_admin'
  AND u.status = 'inactive'
  AND u.deleted_at IS NULL
`

// NOTE: CND-14: 稼働中（status='inactive'・削除除外）の super_admin 数。無効化済み/削除済みは含めない
// （含めると最後の稼働中1人を無効化でき保護が破れる）。UC-014のE4判定に用いる
func (q *Queries) CountActiveSuperAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSuperAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
	user_uuid,
	email,
	password_hash,
	status,
	created_at,
	updated_at
FROM auth.users
WHERE email = $1
  AND deleted_at IS NULL
`

type GetUserByEmailRow struct {
	UserUuid     uuid.UUID
	Email        string
	PasswordHash string
	Status       string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.UserUuid,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUuid = `-- name: GetUserByUuid :one
SELECT
	user_uuid,
	email,
	password_hash,
	status,
	created_at,
	updated_at
FROM auth.users
WHERE user_uuid = $1
  AND deleted_at IS NULL
`

type GetUserByUuidRow struct {
	UserUuid     uuid.UUID
	Email        string
	PasswordHash string
	Status       string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

// NOTE: UC-006: token→user 取得（削除済み除外・E5）
func (q *Queries) GetUserByUuid(ctx context.Context, userUuid uuid.UUID) (GetUserByUuidRow, error) {
	row := q.db.QueryRow(ctx, getUserByUuid, userUuid)
	var i GetUserByUuidRow
	err := row.Scan(
		&i.UserUuid,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserRoles = `-- name: GetUserRoles :many
SELECT
	role
FROM auth.user_roles
WHERE user_uuid = $1
ORDER BY role
`

func (q *Queries) GetUserRoles(ctx context.Context, userUuid uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserRoles, userUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var role string
		if err := rows.Scan(&role); err != nil {
			return nil, err
		}
		items = append(items, role)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertUser = `-- name: InsertUser :exec
INSERT INTO auth.users (
	user_uuid,
	email,
	password_hash,
	status
)
VALUES
	($1, $2, $3, $4)
`

type InsertUserParams struct {
	UserUuid     uuid.UUID
	Email        string
	PasswordHash string
	Status       string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.Exec(ctx, insertUser,
		arg.UserUuid,
		arg.Email,
		arg.PasswordHash,
		arg.Status,
	)
	return err
}

const insertUserRole = `-- name: InsertUserRole :exec
INSERT INTO auth.user_roles (
	user_uuid,
	role
)
VALUES
	($1, $2)
`

type InsertUserRoleParams struct {
	UserUuid uuid.UUID
	Role     string
}

func (q *Queries) InsertUserRole(ctx context.Context, arg InsertUserRoleParams) error {
	_, err := q.db.Exec(ctx, insertUserRole, arg.UserUuid, arg.Role)
	return err
}

const lockActiveSuperAdmins = `-- name: LockActiveSuperAdmins :many
SELECT u.user_uuid
FROM auth.users u
JOIN auth.user_roles ur ON ur.user_uuid = u.user_uuid
WHERE ur.role = 'super_admin'
  AND u.status = 'inactive'
  AND u.deleted_at IS NULL
ORDER BY u.user_uuid
FOR UPDATE OF u
`

// NOTE: CND-14 TOCTOU: 稼働中super_admin行をFOR UPDATEでロックし無効化Tx内で件数評価する（最後の1人保護・UC-014 E4）。
// Tx分離はRepeatableRead（common.UpdateInTx）。並行無効化が先にコミット済みだと本FOR UPDATEは直列化失敗
// （40001）となり、UpdateInTxのリトライが新スナップショットで再評価する＝相手の無効化後の件数で判定される。
// ORDER BYはロック取得順を全Txで一意にしデッドロックを防ぐ（異なる2人の並行無効化が逆順ロックで詰まらない）
func (q *Queries) LockActiveSuperAdmins(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, lockActiveSuperAdmins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_uuid uuid.UUID
		if err := rows.Scan(&user_uuid); err != nil {
			return nil, err
		}
		items = append(items, user_uuid)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transitionUserStatus = `-- name: TransitionUserStatus :execrows
UPDATE auth.users
SET status = $2,
	updated_at = now()
WHERE user_uuid = $1
  AND status = $3
  AND deleted_at IS NULL
`

type TransitionUserStatusParams struct {
	UserUuid uuid.UUID
	Status   string
	Status_2 string
}

func (q *Queries) TransitionUserStatus(ctx context.Context, arg TransitionUserStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, transitionUserStatus, arg.UserUuid, arg.Status, arg.Status_2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserPassword = `-- name: UpdateUserPassword :execrows
UPDATE auth.users
SET password_hash = $2,
    updated_at = now()
WHERE user_uuid = $1
  AND deleted_at IS NULL
`

type UpdateUserPasswordParams struct {
	UserUuid     uuid.UUID
	PasswordHash string
}

// NOTE: UC-010: パスワード更新（削除済み除外）。0行=ユーザー不存在（削除レース）＝呼出側がTx全体を失敗させる
func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserPassword, arg.UserUuid, arg.PasswordHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
