// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package dbmodels

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
	user_uuid,
	email,
	password_hash,
	status,
	created_at,
	updated_at
FROM auth.users
WHERE email = $1
  AND deleted_at IS NULL
`

type GetUserByEmailRow struct {
	UserUuid     uuid.UUID
	Email        string
	PasswordHash string
	Status       string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.UserUuid,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertEmailConfirmationToken = `-- name: InsertEmailConfirmationToken :exec
INSERT INTO auth.email_confirmation_tokens (
	token_uuid,
	user_uuid,
	token_hash,
	expires_at
)
VALUES
	($1, $2, $3, $4)
`

type InsertEmailConfirmationTokenParams struct {
	TokenUuid uuid.UUID
	UserUuid  uuid.UUID
	TokenHash string
	ExpiresAt time.Time
}

func (q *Queries) InsertEmailConfirmationToken(ctx context.Context, arg InsertEmailConfirmationTokenParams) error {
	_, err := q.db.Exec(ctx, insertEmailConfirmationToken,
		arg.TokenUuid,
		arg.UserUuid,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const insertUser = `-- name: InsertUser :exec
INSERT INTO auth.users (
	user_uuid,
	email,
	password_hash,
	status
)
VALUES
	($1, $2, $3, $4)
`

type InsertUserParams struct {
	UserUuid     uuid.UUID
	Email        string
	PasswordHash string
	Status       string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.Exec(ctx, insertUser,
		arg.UserUuid,
		arg.Email,
		arg.PasswordHash,
		arg.Status,
	)
	return err
}

const insertUserRole = `-- name: InsertUserRole :exec
INSERT INTO auth.user_roles (
	user_uuid,
	role
)
VALUES
	($1, $2)
`

type InsertUserRoleParams struct {
	UserUuid uuid.UUID
	Role     string
}

func (q *Queries) InsertUserRole(ctx context.Context, arg InsertUserRoleParams) error {
	_, err := q.db.Exec(ctx, insertUserRole, arg.UserUuid, arg.Role)
	return err
}
