// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package http

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/labstack/echo/v4"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// AdminInvitationRequest defines model for AdminInvitationRequest.
type AdminInvitationRequest struct {
	// Email VAR-01（RFC5322準拠・最大254文字）
	Email openapi_types.Email `json:"email"`

	// Role VAR-09（`super_admin`・`operator`・`system_admin` のいずれか。判定はUseCase層のE2）
	Role string `json:"role"`
}

// ChangePasswordRequest defines model for ChangePasswordRequest.
type ChangePasswordRequest struct {
	// CurrentPassword 現在のパスワード（CND-16照合用。形式検証はしない＝照合失敗として403へ）
	CurrentPassword string `json:"current_password"`

	// NewPassword VAR-02（最小15・最大64文字・Unicode許容・UTF-8で72バイト以下）
	NewPassword string `json:"new_password"`
}

// EmailVerifyRequest defines model for EmailVerifyRequest.
type EmailVerifyRequest struct {
	// Token メール確認トークン（平文。INF-06はSHA-256ハッシュのみ保存し照合する）
	Token string `json:"token"`
}

// EmailVerifyResendRequest defines model for EmailVerifyResendRequest.
type EmailVerifyResendRequest struct {
	// Email VAR-01（RFC5322準拠・最大254文字）
	Email openapi_types.Email `json:"email"`
}

// InvitationAcceptRequest defines model for InvitationAcceptRequest.
type InvitationAcceptRequest struct {
	// Password VAR-02（最小15・最大64文字・Unicode許容・UTF-8で72バイト以下）
	Password string `json:"password"`

	// Token 招待トークン（平文。INF-07はSHA-256ハッシュのみ保存し照合する）
	Token string `json:"token"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	// Email VAR-01（RFC5322準拠・最大254文字）
	Email openapi_types.Email `json:"email"`

	// Password 認証用パスワード（照合はbcrypt・CND-02）
	Password string `json:"password"`
}

// LoginTokens defines model for LoginTokens.
type LoginTokens struct {
	// AccessToken JWT（RS256・INF-03）。sub/roles/exp（VAR-03=15分）クレームを含む
	AccessToken string `json:"access_token"`

	// RefreshToken opaque token（INF-04・NFR-14。base64url。DBにはSHA-256ハッシュのみ保存）
	RefreshToken string `json:"refresh_token"`
}

// LogoutRequest defines model for LogoutRequest.
type LogoutRequest struct {
	// RefreshToken 失効させるopaqueリフレッシュトークン（平文。INF-04はSHA-256ハッシュのみ保存し照合する・UC-007）
	RefreshToken string `json:"refresh_token"`
}

// PasswordChangeResponse defines model for PasswordChangeResponse.
type PasswordChangeResponse struct {
	// RevocationReason 常に password_changed（VAR-10・FR-10。クライアントの再ログイン誘導用。他フィールドなし）
	RevocationReason string `json:"revocation_reason"`
}

// PasswordResetConfirmRequest defines model for PasswordResetConfirmRequest.
type PasswordResetConfirmRequest struct {
	// NewPassword VAR-02（最小15・最大64文字・Unicode許容・UTF-8で72バイト以下）
	NewPassword string `json:"new_password"`

	// Token パスワードリセットトークン（平文。INF-05はSHA-256ハッシュのみ保存し照合する）
	Token string `json:"token"`
}

// PasswordResetRequest defines model for PasswordResetRequest.
type PasswordResetRequest struct {
	// Email VAR-01（RFC5322準拠・最大254文字）
	Email openapi_types.Email `json:"email"`
}

// Problem RFC 9457 Problem Details（NFR-06）。retry_after・revocation_reason は拡張フィールド
type Problem struct {
	Detail *string `json:"detail,omitempty"`

	// ErrorCode 拡張エラーコード（VAR-11＝account_locked 等）
	ErrorCode *string `json:"error_code,omitempty"`
	Instance  *string `json:"instance,omitempty"`

	// RetryAfter レート制限・ロックアウト超過時の再試行可能秒数（E4・VAR-11）
	RetryAfter *int `json:"retry_after,omitempty"`

	// RevocationReason セッション失効理由コード（VAR-10・UC-006の401 session-revokedで使用＝token_reuse_detected/account_deleted/account_disabled）
	RevocationReason *string `json:"revocation_reason,omitempty"`
	Status           int     `json:"status"`
	Title            string  `json:"title"`

	// Type VAR-15のベースURI配下（例 https://example.com/probs/validation-error）
	Type string `json:"type"`
}

// RefreshTokenRequest defines model for RefreshTokenRequest.
type RefreshTokenRequest struct {
	// RefreshToken opaque リフレッシュトークン（平文。INF-04はSHA-256ハッシュのみ保存し照合する・UC-006）
	RefreshToken string `json:"refresh_token"`
}

// RegisterAccountRequest defines model for RegisterAccountRequest.
type RegisterAccountRequest struct {
	// Email VAR-01（RFC5322準拠・最大254文字）
	Email openapi_types.Email `json:"email"`

	// Password VAR-02（最小15文字・最大64文字・文字種の混在強制なし）
	Password string `json:"password"`
}

// InviteAdminJSONRequestBody defines body for InviteAdmin for application/json ContentType.
type InviteAdminJSONRequestBody = AdminInvitationRequest

// VerifyEmailJSONRequestBody defines body for VerifyEmail for application/json ContentType.
type VerifyEmailJSONRequestBody = EmailVerifyRequest

// ResendEmailVerificationJSONRequestBody defines body for ResendEmailVerification for application/json ContentType.
type ResendEmailVerificationJSONRequestBody = EmailVerifyResendRequest

// AcceptInvitationJSONRequestBody defines body for AcceptInvitation for application/json ContentType.
type AcceptInvitationJSONRequestBody = InvitationAcceptRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// LogoutJSONRequestBody defines body for Logout for application/json ContentType.
type LogoutJSONRequestBody = LogoutRequest

// ChangePasswordJSONRequestBody defines body for ChangePassword for application/json ContentType.
type ChangePasswordJSONRequestBody = ChangePasswordRequest

// RequestPasswordResetJSONRequestBody defines body for RequestPasswordReset for application/json ContentType.
type RequestPasswordResetJSONRequestBody = PasswordResetRequest

// ConfirmPasswordResetJSONRequestBody defines body for ConfirmPasswordReset for application/json ContentType.
type ConfirmPasswordResetJSONRequestBody = PasswordResetConfirmRequest

// RegisterAccountJSONRequestBody defines body for RegisterAccount for application/json ContentType.
type RegisterAccountJSONRequestBody = RegisterAccountRequest

// RefreshTokenJSONRequestBody defines body for RefreshToken for application/json ContentType.
type RefreshTokenJSONRequestBody = RefreshTokenRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// 管理者を招待する
	// (POST /admin/invitations)
	InviteAdmin(ctx echo.Context) error
	// メールアドレスを確認する
	// (POST /auth/email-verify)
	VerifyEmail(ctx echo.Context) error
	// メール確認トークンを再送する
	// (POST /auth/email-verify/resend)
	ResendEmailVerification(ctx echo.Context) error
	// 招待を受け付ける
	// (POST /auth/invitation/accept)
	AcceptInvitation(ctx echo.Context) error
	// ログインする
	// (POST /auth/login)
	Login(ctx echo.Context) error
	// ログアウトする
	// (POST /auth/logout)
	Logout(ctx echo.Context) error
	// パスワードを変更する
	// (PUT /auth/password)
	ChangePassword(ctx echo.Context) error
	// パスワードリセットを要求する
	// (POST /auth/password-reset)
	RequestPasswordReset(ctx echo.Context) error
	// パスワードリセットを完了する
	// (POST /auth/password-reset/confirm)
	ConfirmPasswordReset(ctx echo.Context) error
	// アカウントを登録する
	// (POST /auth/register)
	RegisterAccount(ctx echo.Context) error
	// トークンを再発行する
	// (POST /auth/token/refresh)
	RefreshToken(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// InviteAdmin converts echo context to params.
func (w *ServerInterfaceWrapper) InviteAdmin(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.InviteAdmin(ctx)
	return err
}

// VerifyEmail converts echo context to params.
func (w *ServerInterfaceWrapper) VerifyEmail(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.VerifyEmail(ctx)
	return err
}

// ResendEmailVerification converts echo context to params.
func (w *ServerInterfaceWrapper) ResendEmailVerification(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ResendEmailVerification(ctx)
	return err
}

// AcceptInvitation converts echo context to params.
func (w *ServerInterfaceWrapper) AcceptInvitation(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.AcceptInvitation(ctx)
	return err
}

// Login converts echo context to params.
func (w *ServerInterfaceWrapper) Login(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Login(ctx)
	return err
}

// Logout converts echo context to params.
func (w *ServerInterfaceWrapper) Logout(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Logout(ctx)
	return err
}

// ChangePassword converts echo context to params.
func (w *ServerInterfaceWrapper) ChangePassword(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ChangePassword(ctx)
	return err
}

// RequestPasswordReset converts echo context to params.
func (w *ServerInterfaceWrapper) RequestPasswordReset(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RequestPasswordReset(ctx)
	return err
}

// ConfirmPasswordReset converts echo context to params.
func (w *ServerInterfaceWrapper) ConfirmPasswordReset(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ConfirmPasswordReset(ctx)
	return err
}

// RegisterAccount converts echo context to params.
func (w *ServerInterfaceWrapper) RegisterAccount(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RegisterAccount(ctx)
	return err
}

// RefreshToken converts echo context to params.
func (w *ServerInterfaceWrapper) RefreshToken(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RefreshToken(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/admin/invitations", wrapper.InviteAdmin)
	router.POST(baseURL+"/auth/email-verify", wrapper.VerifyEmail)
	router.POST(baseURL+"/auth/email-verify/resend", wrapper.ResendEmailVerification)
	router.POST(baseURL+"/auth/invitation/accept", wrapper.AcceptInvitation)
	router.POST(baseURL+"/auth/login", wrapper.Login)
	router.POST(baseURL+"/auth/logout", wrapper.Logout)
	router.PUT(baseURL+"/auth/password", wrapper.ChangePassword)
	router.POST(baseURL+"/auth/password-reset", wrapper.RequestPasswordReset)
	router.POST(baseURL+"/auth/password-reset/confirm", wrapper.ConfirmPasswordReset)
	router.POST(baseURL+"/auth/register", wrapper.RegisterAccount)
	router.POST(baseURL+"/auth/token/refresh", wrapper.RefreshToken)

}

type InviteAdminRequestObject struct {
	Body *InviteAdminJSONRequestBody
}

type InviteAdminResponseObject interface {
	VisitInviteAdminResponse(w http.ResponseWriter) error
}

type InviteAdmin200Response struct {
}

func (response InviteAdmin200Response) VisitInviteAdminResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type InviteAdmin400ApplicationProblemPlusJSONResponse Problem

func (response InviteAdmin400ApplicationProblemPlusJSONResponse) VisitInviteAdminResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type InviteAdmin401ResponseHeaders struct {
	WWWAuthenticate string
}

type InviteAdmin401ApplicationProblemPlusJSONResponse struct {
	Body    Problem
	Headers InviteAdmin401ResponseHeaders
}

func (response InviteAdmin401ApplicationProblemPlusJSONResponse) VisitInviteAdminResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response.Body)
}

type InviteAdmin403ApplicationProblemPlusJSONResponse Problem

func (response InviteAdmin403ApplicationProblemPlusJSONResponse) VisitInviteAdminResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type InviteAdmin409ApplicationProblemPlusJSONResponse Problem

func (response InviteAdmin409ApplicationProblemPlusJSONResponse) VisitInviteAdminResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type InviteAdmin429ResponseHeaders struct {
	RetryAfter int
}

type InviteAdmin429ApplicationProblemPlusJSONResponse struct {
	Body    Problem
	Headers InviteAdmin429ResponseHeaders
}

func (response InviteAdmin429ApplicationProblemPlusJSONResponse) VisitInviteAdminResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.Header().Set("Retry-After", fmt.Sprint(response.Headers.RetryAfter))
	w.WriteHeader(429)

	return json.NewEncoder(w).Encode(response.Body)
}

type InviteAdmin503ApplicationProblemPlusJSONResponse Problem

func (response InviteAdmin503ApplicationProblemPlusJSONResponse) VisitInviteAdminResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type VerifyEmailRequestObject struct {
	Body *VerifyEmailJSONRequestBody
}

type VerifyEmailResponseObject interface {
	VisitVerifyEmailResponse(w http.ResponseWriter) error
}

type VerifyEmail200Response struct {
}

func (response VerifyEmail200Response) VisitVerifyEmailResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type VerifyEmail400ApplicationProblemPlusJSONResponse Problem

func (response VerifyEmail400ApplicationProblemPlusJSONResponse) VisitVerifyEmailResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type VerifyEmail429ResponseHeaders struct {
	RetryAfter int
}

type VerifyEmail429ApplicationProblemPlusJSONResponse struct {
	Body    Problem
	Headers VerifyEmail429ResponseHeaders
}

func (response VerifyEmail429ApplicationProblemPlusJSONResponse) VisitVerifyEmailResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.Header().Set("Retry-After", fmt.Sprint(response.Headers.RetryAfter))
	w.WriteHeader(429)

	return json.NewEncoder(w).Encode(response.Body)
}

type ResendEmailVerificationRequestObject struct {
	Body *ResendEmailVerificationJSONRequestBody
}

type ResendEmailVerificationResponseObject interface {
	VisitResendEmailVerificationResponse(w http.ResponseWriter) error
}

type ResendEmailVerification200Response struct {
}

func (response ResendEmailVerification200Response) VisitResendEmailVerificationResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type ResendEmailVerification429ResponseHeaders struct {
	RetryAfter int
}

type ResendEmailVerification429ApplicationProblemPlusJSONResponse struct {
	Body    Problem
	Headers ResendEmailVerification429ResponseHeaders
}

func (response ResendEmailVerification429ApplicationProblemPlusJSONResponse) VisitResendEmailVerificationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.Header().Set("Retry-After", fmt.Sprint(response.Headers.RetryAfter))
	w.WriteHeader(429)

	return json.NewEncoder(w).Encode(response.Body)
}

type ResendEmailVerification503ApplicationProblemPlusJSONResponse Problem

func (response ResendEmailVerification503ApplicationProblemPlusJSONResponse) VisitResendEmailVerificationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type AcceptInvitationRequestObject struct {
	Body *AcceptInvitationJSONRequestBody
}

type AcceptInvitationResponseObject interface {
	VisitAcceptInvitationResponse(w http.ResponseWriter) error
}

type AcceptInvitation200Response struct {
}

func (response AcceptInvitation200Response) VisitAcceptInvitationResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type AcceptInvitation400ApplicationProblemPlusJSONResponse Problem

func (response AcceptInvitation400ApplicationProblemPlusJSONResponse) VisitAcceptInvitationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type AcceptInvitation409ApplicationProblemPlusJSONResponse Problem

func (response AcceptInvitation409ApplicationProblemPlusJSONResponse) VisitAcceptInvitationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type AcceptInvitation500ApplicationProblemPlusJSONResponse Problem

func (response AcceptInvitation500ApplicationProblemPlusJSONResponse) VisitAcceptInvitationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200JSONResponse LoginTokens

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type Login400ApplicationProblemPlusJSONResponse Problem

func (response Login400ApplicationProblemPlusJSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type Login401ApplicationProblemPlusJSONResponse Problem

func (response Login401ApplicationProblemPlusJSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type Login403ApplicationProblemPlusJSONResponse Problem

func (response Login403ApplicationProblemPlusJSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type Login429ResponseHeaders struct {
	RetryAfter int
}

type Login429ApplicationProblemPlusJSONResponse struct {
	Body    Problem
	Headers Login429ResponseHeaders
}

func (response Login429ApplicationProblemPlusJSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.Header().Set("Retry-After", fmt.Sprint(response.Headers.RetryAfter))
	w.WriteHeader(429)

	return json.NewEncoder(w).Encode(response.Body)
}

type LogoutRequestObject struct {
	Body *LogoutJSONRequestBody
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout200Response struct {
}

func (response Logout200Response) VisitLogoutResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type Logout400ApplicationProblemPlusJSONResponse Problem

func (response Logout400ApplicationProblemPlusJSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type Logout401ResponseHeaders struct {
	WWWAuthenticate string
}

type Logout401ApplicationProblemPlusJSONResponse struct {
	Body    Problem
	Headers Logout401ResponseHeaders
}

func (response Logout401ApplicationProblemPlusJSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response.Body)
}

type ChangePasswordRequestObject struct {
	Body *ChangePasswordJSONRequestBody
}

type ChangePasswordResponseObject interface {
	VisitChangePasswordResponse(w http.ResponseWriter) error
}

type ChangePassword200JSONResponse PasswordChangeResponse

func (response ChangePassword200JSONResponse) VisitChangePasswordResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ChangePassword400ApplicationProblemPlusJSONResponse Problem

func (response ChangePassword400ApplicationProblemPlusJSONResponse) VisitChangePasswordResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ChangePassword401ResponseHeaders struct {
	WWWAuthenticate string
}

type ChangePassword401ApplicationProblemPlusJSONResponse struct {
	Body    Problem
	Headers ChangePassword401ResponseHeaders
}

func (response ChangePassword401ApplicationProblemPlusJSONResponse) VisitChangePasswordResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response.Body)
}

type ChangePassword403ApplicationProblemPlusJSONResponse Problem

func (response ChangePassword403ApplicationProblemPlusJSONResponse) VisitChangePasswordResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type ChangePassword500ApplicationProblemPlusJSONResponse Problem

func (response ChangePassword500ApplicationProblemPlusJSONResponse) VisitChangePasswordResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type RequestPasswordResetRequestObject struct {
	Body *RequestPasswordResetJSONRequestBody
}

type RequestPasswordResetResponseObject interface {
	VisitRequestPasswordResetResponse(w http.ResponseWriter) error
}

type RequestPasswordReset200Response struct {
}

func (response RequestPasswordReset200Response) VisitRequestPasswordResetResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type RequestPasswordReset400ApplicationProblemPlusJSONResponse Problem

func (response RequestPasswordReset400ApplicationProblemPlusJSONResponse) VisitRequestPasswordResetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type RequestPasswordReset429ResponseHeaders struct {
	RetryAfter int
}

type RequestPasswordReset429ApplicationProblemPlusJSONResponse struct {
	Body    Problem
	Headers RequestPasswordReset429ResponseHeaders
}

func (response RequestPasswordReset429ApplicationProblemPlusJSONResponse) VisitRequestPasswordResetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.Header().Set("Retry-After", fmt.Sprint(response.Headers.RetryAfter))
	w.WriteHeader(429)

	return json.NewEncoder(w).Encode(response.Body)
}

type RequestPasswordReset503ApplicationProblemPlusJSONResponse Problem

func (response RequestPasswordReset503ApplicationProblemPlusJSONResponse) VisitRequestPasswordResetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type ConfirmPasswordResetRequestObject struct {
	Body *ConfirmPasswordResetJSONRequestBody
}

type ConfirmPasswordResetResponseObject interface {
	VisitConfirmPasswordResetResponse(w http.ResponseWriter) error
}

type ConfirmPasswordReset200Response struct {
}

func (response ConfirmPasswordReset200Response) VisitConfirmPasswordResetResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type ConfirmPasswordReset400ApplicationProblemPlusJSONResponse Problem

func (response ConfirmPasswordReset400ApplicationProblemPlusJSONResponse) VisitConfirmPasswordResetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ConfirmPasswordReset500ApplicationProblemPlusJSONResponse Problem

func (response ConfirmPasswordReset500ApplicationProblemPlusJSONResponse) VisitConfirmPasswordResetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type RegisterAccountRequestObject struct {
	Body *RegisterAccountJSONRequestBody
}

type RegisterAccountResponseObject interface {
	VisitRegisterAccountResponse(w http.ResponseWriter) error
}

type RegisterAccount201Response struct {
}

func (response RegisterAccount201Response) VisitRegisterAccountResponse(w http.ResponseWriter) error {
	w.WriteHeader(201)
	return nil
}

type RegisterAccount400ApplicationProblemPlusJSONResponse Problem

func (response RegisterAccount400ApplicationProblemPlusJSONResponse) VisitRegisterAccountResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type RegisterAccount429ResponseHeaders struct {
	RetryAfter int
}

type RegisterAccount429ApplicationProblemPlusJSONResponse struct {
	Body    Problem
	Headers RegisterAccount429ResponseHeaders
}

func (response RegisterAccount429ApplicationProblemPlusJSONResponse) VisitRegisterAccountResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.Header().Set("Retry-After", fmt.Sprint(response.Headers.RetryAfter))
	w.WriteHeader(429)

	return json.NewEncoder(w).Encode(response.Body)
}

type RegisterAccount503ApplicationProblemPlusJSONResponse Problem

func (response RegisterAccount503ApplicationProblemPlusJSONResponse) VisitRegisterAccountResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type RefreshTokenRequestObject struct {
	Body *RefreshTokenJSONRequestBody
}

type RefreshTokenResponseObject interface {
	VisitRefreshTokenResponse(w http.ResponseWriter) error
}

type RefreshToken200JSONResponse LoginTokens

func (response RefreshToken200JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type RefreshToken401ApplicationProblemPlusJSONResponse Problem

func (response RefreshToken401ApplicationProblemPlusJSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// 管理者を招待する
	// (POST /admin/invitations)
	InviteAdmin(ctx context.Context, request InviteAdminRequestObject) (InviteAdminResponseObject, error)
	// メールアドレスを確認する
	// (POST /auth/email-verify)
	VerifyEmail(ctx context.Context, request VerifyEmailRequestObject) (VerifyEmailResponseObject, error)
	// メール確認トークンを再送する
	// (POST /auth/email-verify/resend)
	ResendEmailVerification(ctx context.Context, request ResendEmailVerificationRequestObject) (ResendEmailVerificationResponseObject, error)
	// 招待を受け付ける
	// (POST /auth/invitation/accept)
	AcceptInvitation(ctx context.Context, request AcceptInvitationRequestObject) (AcceptInvitationResponseObject, error)
	// ログインする
	// (POST /auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// ログアウトする
	// (POST /auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// パスワードを変更する
	// (PUT /auth/password)
	ChangePassword(ctx context.Context, request ChangePasswordRequestObject) (ChangePasswordResponseObject, error)
	// パスワードリセットを要求する
	// (POST /auth/password-reset)
	RequestPasswordReset(ctx context.Context, request RequestPasswordResetRequestObject) (RequestPasswordResetResponseObject, error)
	// パスワードリセットを完了する
	// (POST /auth/password-reset/confirm)
	ConfirmPasswordReset(ctx context.Context, request ConfirmPasswordResetRequestObject) (ConfirmPasswordResetResponseObject, error)
	// アカウントを登録する
	// (POST /auth/register)
	RegisterAccount(ctx context.Context, request RegisterAccountRequestObject) (RegisterAccountResponseObject, error)
	// トークンを再発行する
	// (POST /auth/token/refresh)
	RefreshToken(ctx context.Context, request RefreshTokenRequestObject) (RefreshTokenResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// InviteAdmin operation middleware
func (sh *strictHandler) InviteAdmin(ctx echo.Context) error {
	var request InviteAdminRequestObject

	var body InviteAdminJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.InviteAdmin(ctx.Request().Context(), request.(InviteAdminRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "InviteAdmin")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(InviteAdminResponseObject); ok {
		return validResponse.VisitInviteAdminResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// VerifyEmail operation middleware
func (sh *strictHandler) VerifyEmail(ctx echo.Context) error {
	var request VerifyEmailRequestObject

	var body VerifyEmailJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.VerifyEmail(ctx.Request().Context(), request.(VerifyEmailRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "VerifyEmail")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(VerifyEmailResponseObject); ok {
		return validResponse.VisitVerifyEmailResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ResendEmailVerification operation middleware
func (sh *strictHandler) ResendEmailVerification(ctx echo.Context) error {
	var request ResendEmailVerificationRequestObject

	var body ResendEmailVerificationJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ResendEmailVerification(ctx.Request().Context(), request.(ResendEmailVerificationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ResendEmailVerification")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ResendEmailVerificationResponseObject); ok {
		return validResponse.VisitResendEmailVerificationResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// AcceptInvitation operation middleware
func (sh *strictHandler) AcceptInvitation(ctx echo.Context) error {
	var request AcceptInvitationRequestObject

	var body AcceptInvitationJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.AcceptInvitation(ctx.Request().Context(), request.(AcceptInvitationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AcceptInvitation")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(AcceptInvitationResponseObject); ok {
		return validResponse.VisitAcceptInvitationResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Login operation middleware
func (sh *strictHandler) Login(ctx echo.Context) error {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx.Request().Context(), request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		return validResponse.VisitLoginResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Logout operation middleware
func (sh *strictHandler) Logout(ctx echo.Context) error {
	var request LogoutRequestObject

	var body LogoutJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx.Request().Context(), request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		return validResponse.VisitLogoutResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ChangePassword operation middleware
func (sh *strictHandler) ChangePassword(ctx echo.Context) error {
	var request ChangePasswordRequestObject

	var body ChangePasswordJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ChangePassword(ctx.Request().Context(), request.(ChangePasswordRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ChangePassword")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ChangePasswordResponseObject); ok {
		return validResponse.VisitChangePasswordResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// RequestPasswordReset operation middleware
func (sh *strictHandler) RequestPasswordReset(ctx echo.Context) error {
	var request RequestPasswordResetRequestObject

	var body RequestPasswordResetJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RequestPasswordReset(ctx.Request().Context(), request.(RequestPasswordResetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RequestPasswordReset")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(RequestPasswordResetResponseObject); ok {
		return validResponse.VisitRequestPasswordResetResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ConfirmPasswordReset operation middleware
func (sh *strictHandler) ConfirmPasswordReset(ctx echo.Context) error {
	var request ConfirmPasswordResetRequestObject

	var body ConfirmPasswordResetJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ConfirmPasswordReset(ctx.Request().Context(), request.(ConfirmPasswordResetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ConfirmPasswordReset")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ConfirmPasswordResetResponseObject); ok {
		return validResponse.VisitConfirmPasswordResetResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// RegisterAccount operation middleware
func (sh *strictHandler) RegisterAccount(ctx echo.Context) error {
	var request RegisterAccountRequestObject

	var body RegisterAccountJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RegisterAccount(ctx.Request().Context(), request.(RegisterAccountRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RegisterAccount")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(RegisterAccountResponseObject); ok {
		return validResponse.VisitRegisterAccountResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// RefreshToken operation middleware
func (sh *strictHandler) RefreshToken(ctx echo.Context) error {
	var request RefreshTokenRequestObject

	var body RefreshTokenJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RefreshToken(ctx.Request().Context(), request.(RefreshTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RefreshToken")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(RefreshTokenResponseObject); ok {
		return validResponse.VisitRefreshTokenResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
